name: build (windows)

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [ "Win32", "x64" ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Prepare build dir
        run: mkdir build_${{ matrix.arch }}

      - name: Configure (CMake)
        shell: bash
        run: |
          cmake -S . -B build_${{ matrix.arch }} -G "Visual Studio 17 2022" -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release

      - name: Build (Release)
        run: cmake --build build_${{ matrix.arch }} --config Release --parallel

      - name: Collect plugin artifact
        run: |
          mkdir -p artifacts/${{ matrix.arch }}
          # try common output locations; adjust if your CMakeLists emits DLL elsewhere
          cp build_${{ matrix.arch }}/Release/addFont.dll artifacts/${{ matrix.arch }}/ || true
          cp build_${{ matrix.arch }}/Release/*.dll artifacts/${{ matrix.arch }}/ || true
          # fallback: search for addFont.dll anywhere under build dir
          if [ ! -f artifacts/${{ matrix.arch }}/addFont.dll ]; then
            find build_${{ matrix.arch }} -type f -iname "addfont.dll" -exec cp {} artifacts/${{ matrix.arch }}/ \; || true
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: addFont-${{ matrix.arch }}
          path: artifacts/${{ matrix.arch }}
